version: '3.8'
services:
  selenium:
    image: selenium/standalone-chrome:latest
    container_name: selenium
    shm_size: 2gb
    ports:
      - "4444:4444"
    environment:
      - SE_NODE_MAX_SESSIONS=1
      - SE_NODE_CONCURRENT_SESSIONS=1

  mysql:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      - MYSQL_ROOT_PASSWORD=Start123
      - MYSQL_DATABASE=stiebel_eltron
    ports:
      - "3306:3306"
    volumes:
      # 1) Hostpfad : Containerpfad
      - /volume1/docker/selenium:/var/lib/mysql

  app:
    build: .
    container_name: stiebel_eltron
    depends_on:
      - selenium
      - mysql
    environment:
      - MYSQL_HOST=172.17.0.2
      - MYSQL_USER=root
      - MYSQL_PASSWORD=Start123
      - MYSQL_DB=stiebel_eltron
      # 2) Target_Url ist die URL der ISG Stiebel Eltron
      - TARGET_URL=http://192.168.0.100/?s=1,1
